version: "3.9"
services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./backend:/app
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build:
      context: ./chatbot
    ports:
      - "3000:3000"
    volumes:
      - ./chatbot:/app
    stdin_open: true
    tty: true

  ollama:
    image: ollama/mistral:latest
    container_name: mistral
    ports:
      - "11434:11434"
    volumes:
      - ./ollama-data:/data
