version: "3.9"
services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    extra_hosts:
      - "host.docker.internal:host-gateway"  # Allows access to Ollama on the host machine
    environment:
      - PYTHONUNBUFFERED=1
